#!/usr/bin/env python3
"""Regenerate ``src/wifit3/campaigns/wps/wps_router_ouis.py`` from the IEEE OUI registry.

The WPS default-PIN dispatch gates brand-specific generators (D-Link / ASUS / Belkin) to
those vendors' OUIs, so it needs OUI -> vendor for exactly those brands. This script filters
the full ~40k-row IEEE OUI registry down to the ~300 relevant prefixes and emits them as a
Python module.

Usage:
    uv run python scripts/generators/gen_router_ouis.py            # download a fresh registry
    uv run python scripts/generators/gen_router_ouis.py oui.csv    # use a local IEEE csv
"""

from __future__ import annotations

import csv
import io
import sys
import urllib.request
from pathlib import Path

_IEEE_CSV = "https://standards-oui.ieee.org/oui/oui.csv"

# Organization-name substring (lowercased) -> our vendor key. Arcadyan is the ODM behind
# Belkin's Arcadyan-built routers, so it folds into the Belkin family.
_VENDOR_MATCH = {
    "d-link":      "dlink",
    "asus":        "asus",
    "belkin":      "belkin",
    "arcadyan":    "belkin",
    "thomson":     "thomson",
    "technicolor": "thomson",   # Thomson's router line became Technicolor
    "edimax":      "edimax",
    "upvel":       "upvel",
}

_OUT = (Path(__file__).resolve().parents[2]
        / "src" / "wifit3" / "campaigns" / "wps" / "wps_router_ouis.py")


def _vendor_for(org: str) -> str | None:
    low = org.lower()
    for needle, vendor in _VENDOR_MATCH.items():
        if needle in low:
            return vendor
    return None


def _load(source: str | None) -> str:
    if source:
        return Path(source).read_text(encoding="utf-8", errors="replace")
    print(f"Downloading {_IEEE_CSV} ...")
    with urllib.request.urlopen(_IEEE_CSV, timeout=120) as r:  # noqa: S310 (fixed IEEE https host)
        return r.read().decode("utf-8", "replace")


def main(source: str | None = None) -> None:
    mapping: dict[str, str] = {}
    for row in csv.reader(io.StringIO(_load(source))):
        if len(row) < 3 or row[0] != "MA-L":          # header + MA-M/MA-S rows skipped
            continue
        oui, org = row[1].strip().upper(), row[2]
        vendor = _vendor_for(org)
        if vendor and len(oui) == 6 and all(c in "0123456789ABCDEF" for c in oui):
            mapping[oui] = vendor

    header = (
        '"""OUI -> vendor for WPS brand-specific PIN dispatch (D-Link / ASUS / Belkin).\n\n'
        "GENERATED by scripts/generators/gen_router_ouis.py from the IEEE OUI registry\n"
        "(standards-oui.ieee.org). Do NOT edit by hand; rerun the script to refresh.\n"
        "Lazy-imported by wps_algos.pins_for so this table is not loaded until a WPS\n"
        "PIN attack actually starts.\n"
        '"""\n\n'
    )
    body = "OUI_VENDOR = {\n"
    body += "".join(f'    "{o}": "{mapping[o]}",\n' for o in sorted(mapping))
    body += "}\n"
    _OUT.write_text(header + body, encoding="utf-8")

    by: dict[str, int] = {}
    for v in mapping.values():
        by[v] = by.get(v, 0) + 1
    print(f"Wrote {len(mapping)} OUIs -> {_OUT}")
    print("  " + ", ".join(f"{k}={v}" for k, v in sorted(by.items())))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
