#!/usr/bin/env python3
"""Regenerate ``src/wifit3/wlan/fingerprint_categories.py`` from OUI-Master-Database.

Client fingerprinting's low-confidence tier (wlan/fingerprint.py) can only ever name a vendor,
not a device class -- except OUI-Master-Database (github.com/Ringmast4r/OUI-Master-Database, MIT)
already classifies roughly one in six OUIs into a broad category (Camera, Gaming, Router, ...),
aggregated from IEEE + Wireshark + Nmap + a Metasploit-adjacent MAC tracker. Unclassified OUIs
(most of them) are simply absent here, same as they're absent from the source -- never guessed.

This is a genuinely crowd-sourced, occasionally-wrong dataset (spot-checked against our own
hand-verified high-confidence vendors and agreed every time, but it isn't perfect -- see
_CATEGORY_CORRECTIONS below for a real example found during review). Treat a wrong category as
a two-line fix: add the OUI to _CATEGORY_CORRECTIONS here and rerun this script, no need to touch
the upstream project. The category -> emoji mapping is a separate, hand-maintained file
(wlan/device_categories.py) precisely so fixing *that* never requires touching this generator.

Usage:
    uv run python scripts/generators/gen_fingerprint_categories.py                # download fresh
    uv run python scripts/generators/gen_fingerprint_categories.py master_oui.csv # use a local copy
"""
from __future__ import annotations

import csv
import io
import sys
import urllib.request
from pathlib import Path
from typing import Optional

_SOURCE_URL = ("https://raw.githubusercontent.com/Ringmast4r/OUI-Master-Database/master/"
              "LISTS/master_oui.csv")

_OUT = (Path(__file__).resolve().parents[2]
        / "src" / "wifit3" / "wlan" / "fingerprint_categories.py")

# IEEE's allocation widths this source actually uses (in hex nibbles): MA-L/CID share 24 bits,
# MA-M is 28, MA-S/IAB (IAB is MA-S's older name) are 36. Matches fingerprint.py's own
# _PREFIX_LENGTHS -- both walk the same three widths, longest first.
_VALID_LENGTHS = {6, 7, 9}

# A category the source got wrong, found by spot-checking real entries: "Pico-Tesla Magnetic
# Therapies" was tagged Automotive purely because its name contains "Tesla". Map an OUI to a
# corrected category string, or to None to drop the classification entirely (better unclassified
# than wrong). This is the two-line fix mentioned in the module docstring above.
_CATEGORY_CORRECTIONS: dict[str, Optional[str]] = {
    "002510": None,   # Pico-Tesla Magnetic Therapies: not a vehicle
}


def _load(source: str | None) -> str:
    if source:
        return Path(source).read_text(encoding="utf-8", errors="replace")
    print(f"Downloading {_SOURCE_URL} ...")
    req = urllib.request.Request(_SOURCE_URL, headers={"User-Agent": "wifit3-fingerprint-category-gen"})
    with urllib.request.urlopen(req, timeout=120) as r:  # noqa: S310 (fixed github.com https host)
        return r.read().decode("utf-8", "replace")


def main(source: str | None = None) -> None:
    mapping: dict[str, str] = {}
    for row in csv.DictReader(io.StringIO(_load(source))):
        category = (row.get("device_type") or "").strip()
        if not category:
            continue
        hex_digits = (row.get("oui") or "").replace(":", "").replace("-", "").upper()
        if len(hex_digits) not in _VALID_LENGTHS or not all(c in "0123456789ABCDEF" for c in hex_digits):
            continue                          # an allocation width we don't recognize, or bad data
        if hex_digits in _CATEGORY_CORRECTIONS:
            category = _CATEGORY_CORRECTIONS[hex_digits]
            if category is None:
                continue
        mapping[hex_digits] = category

    header = (
        '"""OUI -> broad device category, for client fingerprinting\'s low-confidence tier\n'
        "(wlan/fingerprint.py). Only the ~1-in-6 OUIs the source dataset actually classifies\n"
        "appear here; look up the category's emoji separately in wlan/device_categories.py.\n\n"
        "Keys vary in length (6/7/9 hex chars) the same way fingerprint_vendors.py's do -- some\n"
        "name a 28-/36-bit IEEE sub-allocation, not a plain 24-bit OUI.\n\n"
        "GENERATED by scripts/generators/gen_fingerprint_categories.py from OUI-Master-Database\n"
        "(github.com/Ringmast4r/OUI-Master-Database, MIT). Do NOT edit by hand -- to fix a wrong\n"
        "category, add it to that script's _CATEGORY_CORRECTIONS and rerun; to change an emoji,\n"
        'edit wlan/device_categories.py instead, not this file.\n"""\n\n'
    )
    body = "OUI_CATEGORY = {\n"
    body += "".join(f'    "{o}": {mapping[o]!r},\n' for o in sorted(mapping))
    body += "}\n"
    _OUT.write_text(header + body, encoding="utf-8")
    print(f"Wrote {len(mapping)} categorized OUIs -> {_OUT}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
