#!/usr/bin/env python3
"""Regenerate ``src/wifit3/wlan/fingerprint_vendors.py`` from the IEEE OUI registry.

Client fingerprinting's low-confidence tier (wlan/fingerprint.py) names a client's vendor
without claiming a specific device class -- unlike gen_router_ouis.py (which filters the ~40k-row
registry down to ~300 router-brand prefixes for a narrow purpose), this keeps every MA-L
organization: broad "who made this" coverage is the entire point of the low-confidence tier, so
there's no vendor allowlist to filter against. Organization names are cleaned up (corporate
suffixes stripped, ALL-CAPS title-cased) so the popup shows "Samsung Electronics", not
"SAMSUNG ELECTRONICS CO.,LTD".

Usage:
    uv run python scripts/generators/gen_fingerprint_vendors.py            # download a fresh registry
    uv run python scripts/generators/gen_fingerprint_vendors.py oui.csv    # use a local IEEE csv
"""
from __future__ import annotations

import csv
import io
import re
import sys
import urllib.request
from pathlib import Path

_IEEE_CSV = "https://standards-oui.ieee.org/oui/oui.csv"

_OUT = (Path(__file__).resolve().parents[2]
        / "src" / "wifit3" / "wlan" / "fingerprint_vendors.py")

# Stripped iteratively (some names stack two, e.g. "X Technology Co., Ltd."), so each pattern
# only needs to match one trailing suffix at a time.
_SUFFIX_RE = re.compile(
    r",?\s*("
    r"incorporated|inc\.?|llc\.?|ltd\.?|co\.,?\s*ltd\.?|corporation|corp\.?|gmbh|"
    r"s\.a\.?|s\.p\.a\.?|b\.v\.?|pty\.?\s*ltd\.?|pvt\.?\s*ltd\.?|ag|company|limited"
    r")\.?\s*$",
    re.IGNORECASE,
)


def _clean_name(org: str) -> str:
    name = org.strip().strip('"').strip()
    # The IEEE registry is free text: a handful of orgs registered trademark glyphs or an
    # em-dash into their own name (e.g. "Planet Bingo® — 3rd Rock Gaming®"), which the
    # project's own em-dash ban would otherwise trip on generated output.
    name = name.replace("—", "-").replace("–", "-")
    name = name.replace("®", "").replace("™", "")
    prev = None
    while prev != name and name:
        prev = name
        name = _SUFFIX_RE.sub("", name).strip()
    if not name:
        return org.strip()
    return name.title() if name.isupper() else name


def _load(source: str | None) -> str:
    if source:
        return Path(source).read_text(encoding="utf-8", errors="replace")
    print(f"Downloading {_IEEE_CSV} ...")
    with urllib.request.urlopen(_IEEE_CSV, timeout=120) as r:  # noqa: S310 (fixed IEEE https host)
        return r.read().decode("utf-8", "replace")


def main(source: str | None = None) -> None:
    mapping: dict[str, str] = {}
    for row in csv.reader(io.StringIO(_load(source))):
        if len(row) < 3 or row[0] != "MA-L":          # header + MA-M/MA-S rows skipped
            continue
        oui = row[1].strip().upper()
        if len(oui) != 6 or not all(c in "0123456789ABCDEF" for c in oui):
            continue
        mapping[oui] = _clean_name(row[2])

    header = (
        '"""OUI -> cleaned vendor name, for client fingerprinting\'s low-confidence tier\n'
        "(wlan/fingerprint.py): every registered vendor, since naming who made a device --\n"
        "without claiming which kind -- is the entire point of that tier.\n\n"
        "GENERATED by scripts/generators/gen_fingerprint_vendors.py from the IEEE OUI registry\n"
        '(standards-oui.ieee.org). Do NOT edit by hand; rerun the script to refresh.\n"""\n\n'
    )
    body = "VENDOR_BY_OUI = {\n"
    body += "".join(f'    "{o}": {mapping[o]!r},\n' for o in sorted(mapping))
    body += "}\n"
    _OUT.write_text(header + body, encoding="utf-8")
    print(f"Wrote {len(mapping)} OUIs -> {_OUT}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
